apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: myuiapp
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: myuiapp
  service:
    name: myuiapp
    port: 8080
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
