FROM node:latest

RUN apt-get update -y
RUN apt-get install nginx -y

WORKDIR /app
COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org
RUN npm install
COPY . .
#RUN npm install
RUN npm run-script build
WORKDIR /app/dist
RUN rm -r /usr/share/nginx/html/*
RUN cp -r /app/dist/* /usr/share/nginx/html/
EXPOSE 8080
EXPOSE 80

CMD ["nginx","-g","daemon off;"]